=== *Отчёт по лабораторной работе 1*

Студент: Зернов И.В.

Группа: ПИМ-22

==== 1. Постановка задачи

В процессе выполнения лабораторной работы необходимо выполнить следующие задачи:

. Создать исполняемый java класс, который выводит текстовую строку на экран.
. Разработать два класса. Первый класс вызывает два метода из второго класса (статический и нестатический).
. Создать jar-файл, хранящий элементы из предыдущего задания.

==== 2. Структура проекта

Проект разделён на следующие директории

. *JavaLabs* - основная папка с файлами, содержит **classes, src, manifest.mf**;
. *classes* - папка, в которой хранятся классы;
. *src* - папка с файлами .java

==== 3. Информация о реализации

Папки создавались без использования командной строки, так как выполнение лабораторной работы проводилось на Windows.
Также результат выполнения лабораторной работы не разделён на отдельные файлы, а собран в два класса, в которых выполняются все необходимые действия.

==== 4. Выполнение задания

Для выполнения данного задания был создан исполняемый класс HelloWorld

 package ru.rsatu.lr1;
 public class HelloWorld {
	static String HW="Hello World!";
	public static void Hello(){
		System.out.println(HW);
	}
	public void Dynamic(){
		System.out.println("And to you too");
	}
}

Который выводит на экран строку "Hello World!", а также имеет метод Dynamic, который будет вызван классом NewClass

 package ru.rsatu.lr1;
 import ru.rsatu.lr1.HelloWorld;
 public class NewClass{
	public static void main(String[] args){
		System.out.println("I'm gonna say Hello");
		HelloWorld.Hello();
		HelloWorld dyn = new HelloWorld();
		dyn.Dynamic();
	}
}

NewClass - Выводит строку "I'm gonna say Hello" на экран, вызывает статическую функцию из класса HelloWorld, создаёт экземпляр и вызывает динамическую функцию Dynamic.

Для создания файлов класса были использованы следующие команды
 
 javac -cp classes/ -d classes/ src/ru/rsatu/lr1/HelloWorld.java
 javac -cp classes/ -d classes/ src/ru/rsatu/lr1/NewClass.java

После выполнения команд в папке classes..lr1 были созданы файлы классов HelloWorld и NewClass

Результат выполнения программы:
 
 java -cp classes ru/rsatu/lr1/NewClass
 I'm gonna say Hello
 Hello World!
 And to you too
 
Для помещения файлов в jar архив была использована следующая команда:

 jar cvmf manifest.mf NewClass.jar -C classes ru/rsaru/lr1
 
 java -jar NewClass.jar
 I'm gonna say Hello
 Hello World!
 And to you too
 
==== 5. Вывод

В результате выполнения лабораторной работы были получены базовые знания написания программ на языке java, использования командной строки для создания файлов .class и общей работы с файлами, запаковывания файлов в исполняемый архив .jar. Также были получены навыки работы в формате asciidoc.
 
